SET(SPINNAKER_ROOT "/usr")

SET(SPINNAKER_TEST_INCLUDE_PATHS ${SPINNAKER_ROOT}/include/spinnaker)
SET(SPINNAKER_TEST_LIB_PATHS ${SPINNAKER_ROOT}/lib)
FIND_PATH(SPINNAKER_INCLUDE_PATH Spinnaker.h
  ${SPINNAKER_TEST_INCLUDE_PATHS}
  )
FIND_LIBRARY(SPINNAKER_LIBRARY Spinnaker ${SPINNAKER_TEST_LIB_PATHS})
SET(SPINNAKER_LIBRARIES ${SPINNAKER_LIBRARY})
SET(SPINNAKER_INCLUDE_DIRS ${SPINNAKER_INCLUDE_PATH})
