SET(LIBSERIAL_ROOT "/usr")

SET(LIBSERIAL_TEST_INCLUDE_PATHS ${LIBSERIAL_ROOT}/include/)
SET(LIBSERIAL_TEST_LIB_PATHS ${LIBSERIAL_ROOT}/lib)
FIND_PATH(LIBSERIAL_INCLUDE_PATH SerialStream.h
  ${LIBSERIAL_TEST_INCLUDE_PATHS}
  )
FIND_LIBRARY(LIBSERIAL_LIBRARY libserial.so ${LIBSERIAL_TEST_LIB_PATHS})
SET(LIBSERIAL_LIBRARIES ${LIBSERIAL_LIBRARY})
SET(LIBSERIAL_INCLUDE_DIRS ${LIBSERIAL_INCLUDE_PATH})
